import { NextResponse } from 'next/server';
import { getSession } from '@/lib/session';
import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

interface ExportRequest {
  checkRunId: string;
  repoName: string;
  branchName?: string;
  checkType?: string;
  summary: {
    totalIssues: number;
    highSeverity: number;
    mediumSeverity: number;
    lowSeverity: number;
  };
  issues: Array<{
    severity: 'high' | 'medium' | 'low';
    category: string;
    description: string;
    solution: string;
    file?: string;
    ruleId?: string;
    aiPinpointLocation?: {
      filePath: string;
      lineNumbers: number[];
    };
    aiSuggestedFix?: {
      explanation: string;
      codeSnippet: string;
    };
  }>;
}

export async function POST(request: Request) {
  const session = await getSession();

  if (!session.isLoggedIn) {
    return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  }

  try {
    const body: ExportRequest = await request.json();
    const { repoName, branchName, checkType, summary, issues } = body;

    console.log(`[Report Export] Generating report for ${repoName} with ${issues.length} issues`);

    // Generate the markdown report using AI
    const markdown = await generateMarkdownReport({
      repoName,
      branchName,
      checkType,
      summary,
      issues,
    });

    return NextResponse.json({
      success: true,
      markdown,
    });
  } catch (error) {
    console.error('Report export error:', error);
    return NextResponse.json(
      { error: 'Failed to generate report' },
      { status: 500 }
    );
  }
}

async function generateMarkdownReport(data: {
  repoName: string;
  branchName?: string;
  checkType?: string;
  summary: ExportRequest['summary'];
  issues: ExportRequest['issues'];
}): Promise<string> {
  try {
    const model = genAI.getGenerativeModel({ model: 'gemini-3.0-flash' });

    const platformMap: { [key: string]: string } = {
      'APPLE_APP_STORE': 'Apple App Store',
      'GOOGLE_PLAY_STORE': 'Google Play Store',
      'CHROME_WEB_STORE': 'Chrome Web Store',
      'MOBILE_PLATFORMS': 'Mobile Platforms (iOS & Android)',
    };

    const platformName = data.checkType ? platformMap[data.checkType] || data.checkType : 'Unknown Platform';

    const prompt = `You are Themis, an AI compliance expert. Generate a comprehensive, professional Markdown report for a compliance check.

Repository: ${data.repoName}
Branch: ${data.branchName || 'main'}
Platform: ${platformName}
Check Date: ${new Date().toISOString().split('T')[0]}

Summary:
- Total Issues: ${data.summary.totalIssues}
- High Severity: ${data.summary.highSeverity}
- Medium Severity: ${data.summary.mediumSeverity}
- Low Severity: ${data.summary.lowSeverity}

Issues Details:
${JSON.stringify(data.issues, null, 2)}

Create a well-structured Markdown report with:
1. Professional header with repository info and summary
2. Executive summary with key findings
3. Detailed issues organized by severity (Critical/High, Medium, Low)
4. For each issue include:
   - Rule ID and category
   - Clear description of the violation
   - AI-pinpointed code location (if available)
   - Recommended solution with code snippets (if available)
   - Affected files
5. Recommendations section
6. Professional footer

Use proper Markdown formatting with headers, code blocks, tables, and emphasis.
Make it suitable for technical teams and compliance officers.
Be concise but comprehensive.`;

    const result = await model.generateContent(prompt);
    const markdown = result.response.text();

    console.log(`[Report Export] Generated ${markdown.length} character report`);
    return markdown;
  } catch (error) {
    console.error('[Report Export] AI generation failed:', error);
    
    // Fallback to template-based report if AI fails
    return generateFallbackReport(data);
  }
}

function generateFallbackReport(data: {
  repoName: string;
  branchName?: string;
  checkType?: string;
  summary: ExportRequest['summary'];
  issues: ExportRequest['issues'];
}): string {
  const today = new Date().toISOString().split('T')[0];
  const platformMap: { [key: string]: string } = {
    'APPLE_APP_STORE': 'Apple App Store',
    'GOOGLE_PLAY_STORE': 'Google Play Store',
    'CHROME_WEB_STORE': 'Chrome Web Store',
    'MOBILE_PLATFORMS': 'Mobile Platforms (iOS & Android)',
  };
  const platformName = data.checkType ? platformMap[data.checkType] || data.checkType : 'Unknown Platform';

  let markdown = `# Compliance Report

**Repository:** ${data.repoName}  
**Branch:** ${data.branchName || 'main'}  
**Platform:** ${platformName}  
**Generated:** ${today}  
**Generated by:** Themis Compliance Engine

---

## Executive Summary

This report contains the results of an automated compliance check performed on **${data.repoName}**.

### Issue Summary

| Severity | Count |
|----------|-------|
| **Critical/High** | ${data.summary.highSeverity} |
| **Medium** | ${data.summary.mediumSeverity} |
| **Low** | ${data.summary.lowSeverity} |
| **Total** | ${data.summary.totalIssues} |

`;

  if (data.summary.totalIssues === 0) {
    markdown += `## ✅ All Clear!

No compliance issues were found in this repository. Your code meets all the checked compliance requirements.

`;
  } else {
    // Group issues by severity
    const highIssues = data.issues.filter(i => i.severity === 'high');
    const mediumIssues = data.issues.filter(i => i.severity === 'medium');
    const lowIssues = data.issues.filter(i => i.severity === 'low');

    // High severity issues
    if (highIssues.length > 0) {
      markdown += `## 🚨 Critical/High Severity Issues

`;
      highIssues.forEach((issue, index) => {
        markdown += `### ${index + 1}. ${issue.category}

**Rule ID:** ${issue.ruleId || 'N/A'}  
**Severity:** High  
${issue.file ? `**File:** \`${issue.file}\`  ` : ''}

**Description:**  
${issue.description}

**Solution:**  
${issue.solution}

${issue.aiPinpointLocation ? `**Code Location:**  
File: \`${issue.aiPinpointLocation.filePath}\`  
Lines: ${issue.aiPinpointLocation.lineNumbers.join(', ')}

` : ''}${issue.aiSuggestedFix ? `**AI Suggested Fix:**  
${issue.aiSuggestedFix.explanation}

\`\`\`
${issue.aiSuggestedFix.codeSnippet}
\`\`\`

` : ''}---

`;
      });
    }

    // Medium severity issues
    if (mediumIssues.length > 0) {
      markdown += `## ⚠️ Medium Severity Issues

`;
      mediumIssues.forEach((issue, index) => {
        markdown += `### ${index + 1}. ${issue.category}

**Rule ID:** ${issue.ruleId || 'N/A'}  
**Severity:** Medium  
${issue.file ? `**File:** \`${issue.file}\`  ` : ''}

**Description:**  
${issue.description}

**Solution:**  
${issue.solution}

${issue.aiPinpointLocation ? `**Code Location:**  
File: \`${issue.aiPinpointLocation.filePath}\`  
Lines: ${issue.aiPinpointLocation.lineNumbers.join(', ')}

` : ''}${issue.aiSuggestedFix ? `**AI Suggested Fix:**  
${issue.aiSuggestedFix.explanation}

\`\`\`
${issue.aiSuggestedFix.codeSnippet}
\`\`\`

` : ''}---

`;
      });
    }

    // Low severity issues
    if (lowIssues.length > 0) {
      markdown += `## ℹ️ Low Severity Issues

`;
      lowIssues.forEach((issue, index) => {
        markdown += `### ${index + 1}. ${issue.category}

**Rule ID:** ${issue.ruleId || 'N/A'}  
**Severity:** Low  
${issue.file ? `**File:** \`${issue.file}\`  ` : ''}

**Description:**  
${issue.description}

**Solution:**  
${issue.solution}

${issue.aiPinpointLocation ? `**Code Location:**  
File: \`${issue.aiPinpointLocation.filePath}\`  
Lines: ${issue.aiPinpointLocation.lineNumbers.join(', ')}

` : ''}${issue.aiSuggestedFix ? `**AI Suggested Fix:**  
${issue.aiSuggestedFix.explanation}

\`\`\`
${issue.aiSuggestedFix.codeSnippet}
\`\`\`

` : ''}---

`;
      });
    }
  }

  markdown += `## Recommendations

${data.summary.highSeverity > 0 ? '1. **Priority:** Address all critical/high severity issues immediately as they may prevent app store approval.\n' : ''}${data.summary.mediumSeverity > 0 ? '2. **Important:** Review and fix medium severity issues to improve compliance posture.\n' : ''}${data.summary.lowSeverity > 0 ? '3. **Enhancement:** Consider addressing low severity issues for best practices.\n' : ''}${data.summary.totalIssues === 0 ? '- Continue following current development practices\n- Regular compliance checks are recommended\n' : ''}
---

*This report was generated by Themis Compliance Engine on ${today}*
`;

  return markdown;
}